### ISSUE TITLE
链接配置有误

### ISSUE THREAD

**Issue by geekyouth** [CoderMing/blogsue#1]
![image](https://user-images.githubusercontent.com/12899262/45257649-62689c00-b3dc-11e8-9ba2-79b2ff5b454c.png)

![image](https://user-images.githubusercontent.com/12899262/45257650-65638c80-b3dc-11e8-95cd-65a2fe67ea5e.png)

**Comment by CoderMing** [comment]
@geekyouth 这个是你申请的app key的回调地址。你检查一下，回调地址是否填写正确？

**Comment by CoderMing** [comment]
@geekyouth sorry，已修改。
