### ISSUE TITLE
自动构建最新的image，不再需要再本地 docker build

### ISSUE THREAD

**Issue by iamwwc** [CoderMing/blogsue#9]
#### 背景
当使用新机器时，每次都需要创建 index.js 文件，然后手动编译，耗时长，流程繁琐

#### 如何解决？

我们需要将配置文件预先存放到 gist（或者 github repo）。

travis 编译时会通过脚本先获取配置文件，然后添加到  src/config/index.js 中，

之后会配合 `npm install && npm run` 编译出最新代码，然后将镜像推送到 docker hub。

使用时只需要

`docker run --name blogsue -d -p 8080:8080 iamwwc/blogsue`

就可通过公网访问到 8080 的服务（需要 iptables 开放端口）

你需要 `fork` 本项目，然后在 `travis` 界面添加以下环境变量

`DOCKER_LOGIN_USER_NAME` 你的 `docker hub` 登陆名

`DOCKER_LOGIN_PASSWORD` 你的 `docker hub` 登陆密码

`ENV_URL` 配置文件来源URL，你可以使用 `gist`，然后发布成 `secret` 版本，请确保请求到的是原始文本，如果你使用 `gist`，则以 `raw` 开头

`IMAGE_NAME` 镜像名字，默认 `blogsue`，请确保这里的名字与 上面的 `dockerhub` 仓库名 相同

这里是我提交的代码

https://github.com/iamwwc/blogsue

你可以向我反馈这种设计的问题。是否有必要合并到 `coderming/blogsue:master`

**Comment by CoderMing** [comment]
nice~

**Comment by fydy** [comment]
ENV_URL 配置文件来源URL，gist指什么，在哪里获取？

**Comment by fydy** [comment]
博客利用用到的图标 icon 在哪里获取？

**Comment by CoderMing** [comment]
> 博客利用用到的图标 icon 在哪里获取？
https://blueprintjs.com/docs/#icons
